### ISSUE TITLE
Snippets not showing under suggestions

### ISSUE THREAD

**Issue by gregcousin126** [amandeepmittal/expressjs#3]
Hello, I am having trouble seeing the snippets appear on my suggestions in the editor after downloading your plugin via vscode on a mac. Is there a way you can point me in the right direction?

**Comment by amandeepmittal** [comment]
HI @gregcousin126, I am currently using it in vscode (_my vscode version is 1.22.2_) and it is working fine for me. Are you using this vscode package: https://github.com/amandeepmittal/expressjs-vscode? Also what is exactly the trouble you are referring to?

**Comment by gregcousin126** [comment]
Hello @amandeepmittal, I figured out what the issue was. I went ahead and looked around my snippet file folder and for some reason the javascript.json was encoded in weird ways. I went ahead and reinstalled vscode and everything came back to normal and the snippets work again. Thank you for them!!!

**Comment by amandeepmittal** [comment]
I am glad you figured it out. Great! I do hope these snippets make you work a bit faster. 👍
